// src/components/lessons/games/finger-sum-game/fingerImages.ts

export const fingerImages: { [key: number]: string } = {
  0: '/icons/img_0dedos.jpg',
  1: '/icons/img_1dedo.jpg',
  2: '/icons/img_2dedos.jpg',
  3: '/icons/img_3dedos.jpg',
  4: '/icons/img_4dedos.jpg',
  5: '/icons/img_5dedos.jpg',
  6: '/icons/img_6dedos.jpg',
  7: '/icons/img_7dedos.jpg',
  8: '/icons/img_8dedos.jpg',
  9: '/icons/img_9dedos.jpg',
  10: '/icons/img_10dedos.jpg',
  11: '/icons/11.jpg',
  12: '/icons/12.jpg',
  13: '/icons/13.jpg',
  14: '/icons/14.jpg',
  15: '/icons/15.jpg',
  16: '/icons/16.jpg',
  17: '/icons/17.jpg',
  18: '/icons/18.jpg',
  19: '/icons/19.jpg',
  20: '/icons/20.png',
};
